Update 04.05.10-FW27

diff --git a/ptxproj/projectroot/etc/config-tools/config_interfaces b/ptxproj/projectroot/etc/config-tools/config_interfaces
--- a/ptxproj/projectroot/etc/config-tools/config_interfaces
+++ b/ptxproj/projectroot/etc/config-tools/config_interfaces
@@ -24,7 +24,7 @@
 
 # load general definitions and functions
 if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
-  echo "config_tool_lib missing"
+  echo "config_tool_lib missing" 
   exit 64
 fi
 
@@ -61,7 +61,8 @@ function convert_bridge_to_port {
 
 status=$SUCCESS
 
-if [[ $# -lt 1 ]]; then
+if [[ $# -lt 2 ]]; then
+    SetLastError "config_interfaces: error - number of parameters" 
     exit 1
 fi
 
@@ -101,6 +102,7 @@ while [[ $# -ne 0 ]]; do
             broadcast="${1#broadcast=}"
             ;;
         *)
+            SetLastError "config_interfaces: error - invalid parameter"
             exit $INVALID_PARAMETER
             ;;
     esac
@@ -108,21 +110,28 @@ while [[ $# -ne 0 ]]; do
 done
 
 if [[ -z "$port" ]]; then
+    SetLastError "config_interfaces: error - empty port name"
     exit 1
 fi
 
 if [[ -z "$state" && -z "$source" && -z "$ipaddr" && -z "$netmask" && -z "$broadcast" ]]; then
-    exit 1
+   SetLastError "config_interfaces: error - missing one of parameter (state, config-type, ip-address, subnet-mask, broadcast)" 
+   exit 1
 fi
 
 bridge=$(convert_port_to_bridge "$port")
 if [[ -z $bridge ]]; then
+    SetLastError "config_interfaces: error - determine bridge value"
     exit $INVALID_PARAMETER
 fi
 
 if [[ -n "$state" ]]; then
-	$IFCONFIG "$bridge" "${state_map[$state]}"
+	msg=$($IFCONFIG "$bridge" "${state_map[$state]}" 2>&1 ) 
 	status=$?
+        if [[ "$status" != $SUCCESS ]]; then
+           SetLastError "config_interfaces: error - ifconfig: " $msg
+           exit $status
+        fi
 fi
 
 if [[ "$status" == $SUCCESS && ( -n "$source" || -n "$ipaddr" || -n "$netmask" ) ]]; then
@@ -137,8 +146,9 @@ if [[ "$status" == $SUCCESS && ( -n "$source" || -n "$ipaddr" || -n "$netmask" )
     fi
 
     json_string="{\"$bridge\":{\"source\":\"$source\",\"ipaddr\":\"$ipaddr\",\"netmask\":\"$netmask\"}}"
-    result=$($NETWORK_CONFIG --ip-config --set $json_string --format=json)
+    result=$($NETWORK_CONFIG --ip-config --set $json_string --format=json 2>&1 )
     status=$?
+    SetLastError "config_interfaces: error - " $result
 fi
 
 exit $status
diff --git a/ptxproj/projectroot/etc/config-tools/events/networking/update_config b/ptxproj/projectroot/etc/config-tools/events/networking/update_config
--- a/ptxproj/projectroot/etc/config-tools/events/networking/update_config
+++ b/ptxproj/projectroot/etc/config-tools/events/networking/update_config
@@ -4,7 +4,7 @@
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 #
-# Copyright (c) 2018-2022 WAGO GmbH & Co. KG
+# Copyright (c) 2018-2024 WAGO GmbH & Co. KG
 
 #-----------------------------------------------------------------------------#
 # Script-name: update_config
@@ -18,6 +18,7 @@
 
 set -u # error exit on undefined shell variables
 
+dnsmasq_config_changed=false
 
 function DomainToResolvConf() {
     local validdomain=$1
@@ -37,10 +38,74 @@ function DomainToResolvConf() {
     fi
 }
 
+#Writing the domain to dnsmasq_default configuration file.
+#The file /etc/dnsmasq.conf can't be used because it is
+#rewritten on every dnsmasq configuration change from WBM/CBM.
+function DomainToDNSMASQ() {
+    local domain=$1
+    local dnsmasq_conf=/etc/dnsmasq.d/dnsmasq_default.conf
+
+    #get actual domain
+    local act_domain=""
+    IFS="=" read -r dummy act_domain <<<"$(grep -E '^domain=' $dnsmasq_conf)"
+
+    if [ "$act_domain" != "$domain" ]; then
+        if [ "$domain" ]; then
+            #check if act_domain differs from new_domain
+            local domain_search="/^\(#\)\?domain=.*"
+
+            #search for the first '#domain=' or 'domain=' at the beginning of the line
+            #replace it with 'domain=$domain'
+            sed -i -e "1,$domain_search/{$domain_search/s//domain=$domain/}" $dnsmasq_conf
+        else
+            #no domain -> we have to comment the domain-parameter (#domain=)
+            #otherwise dmasq will fail during startup
+            sed -i -e "/^domain=/c#domain=" $dnsmasq_conf
+        fi
+        # We have to restart dnsmasq to re-read the configuration.
+        dnsmasq_config_changed=true
+    fi
+}
+
+function UpdateDnsmasqConfig() {
+    local DNSMASQ_CONFIG="/etc/dnsmasq.conf"
+    local DNSMASQ_CONFIG_TMP="/tmp/dnsmasq.conf"
+    local NET_PARAMS=""
+
+    if [[ -n ${NETCONF_BRIDGE_CONFIG+x} && -n ${NETCONF_IP_CONFIG+x} && -n ${NETCONF_INTERFACE_CONFIG+x} && -n ${NETCONF_INTERFACE_STATUSES+x} ]]; then
+        NET_PARAMS="--bridge-config $NETCONF_BRIDGE_CONFIG --ip-config $NETCONF_IP_CONFIG --interface-config $NETCONF_INTERFACE_CONFIG --interface-statuses $NETCONF_INTERFACE_STATUSES"
+    fi
+
+    /etc/config-tools/config_dnsmasq_c --gen-config --no-dnsmasq-restart --dnsmasq-config $DNSMASQ_CONFIG_TMP $NET_PARAMS
+
+    if ! diff -q $DNSMASQ_CONFIG $DNSMASQ_CONFIG_TMP; then
+        mv $DNSMASQ_CONFIG_TMP $DNSMASQ_CONFIG
+        sync
+        dnsmasq_config_changed=true
+    fi
+
+    if [[ -e $DNSMASQ_CONFIG_TMP ]]; then
+        rm -f $DNSMASQ_CONFIG_TMP &>/dev/null
+    fi
+}
+
 # main: set global variables
 PATH="/bin:/sbin:/usr/bin:/usr/sbin"
 
 validdomain="$(dnsdomainname)"
 
 DomainToResolvConf "$validdomain"
+DomainToDNSMASQ "$validdomain"
 
+# dnsmasq update relies on /etc/hosts too. Therefore, run dnsmasq update after UpdateHostConf part.
+UpdateDnsmasqConfig
+
+if [[ "$dnsmasq_config_changed" == true ]]; then
+    # We have to restart dnsmasq to re-read the configuration.
+    # Use the "update" option to avoid regenerating the file /etc/dnsmasq.conf .
+    # The generation was already done during UpdateDnsmasqConfig execution.
+    /etc/init.d/dnsmasq update
+else
+    # just sighup to reload hosts
+    /etc/init.d/dnsmasq reload
+fi
diff --git a/ptxproj/projectroot/etc/init.d/link_devices b/ptxproj/projectroot/etc/init.d/link_devices
--- a/ptxproj/projectroot/etc/init.d/link_devices
+++ b/ptxproj/projectroot/etc/init.d/link_devices
@@ -1,10 +1,25 @@
 #!/bin/bash
+#-----------------------------------------------------------------------------#
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
 #
-# link devices
+# Copyright (c) 2015-2024 WAGO GmbH & Co. KG
+#-----------------------------------------------------------------------------#
+#-----------------------------------------------------------------------------#
+# Script:   /etc/init.d/link_devices
 #
-
-# this script link devices from sys-fs to /dev/. The devices that
-# need to be linked are defined in /etc/specific/.devs_to_link.
+# Brief:    Init script to link selected devices to well known names.
+#           Some link targets read from sys-fs.
+#           A collection of needed links is defined in
+#           /etc/specific/.devs_to_link.
+#
+# Author:   OK:   WAGO GmbH & Co. KG
+# Author:   AGa:  WAGO GmbH & Co. KG
+# Author:   HFS:  WAGO GmbH & Co. KG
+# Author:   PEn:  WAGO GmbH & Co. KG
+# Author:   LHe:  WAGO GmbH & Co. KG
+#-----------------------------------------------------------------------------#
 
 DEVS_TO_LINK="/etc/specific/.devs_to_link"
 DEV_SEARCH_PATH="/sys/devices/"
@@ -24,17 +39,6 @@ check_unnamed()
     return 0
 }
 
-extract_nand_label()
-{
-    local ubi_device="$1"
-
-    local name=""
-    name="$(cat "/sys/class/ubi/$ubi_device/name")"
-    check_unnamed $? "$name" "$ubi_device"
-
-    return 0
-}
-
 extract_emmc_label()
 {
     local partition_device="$1"
@@ -47,63 +51,44 @@ extract_emmc_label()
 }
 
 
-if [[ -c "/dev/mtd8" ]]; then
-    detach_ubi=false
-    if [[ ! -e "/sys/class/ubi/ubi0_0" ]]; then
-        /sbin/ubiattach --mtdn=8 &>/dev/null
-        detach_ubi=true
-    fi
-    # static partitions for systems with internal flash nand
-    PARTITION_NAND_ROOTFS1_DEV_NAME="ubi0_0"
-    PARTITION_NAND_ROOTFS1_LINK_NAME="/dev/partition_$(extract_nand_label "$PARTITION_NAND_ROOTFS1_DEV_NAME")"
-    PARTITION_NAND_ROOTFS2_DEV_NAME="ubi0_2"
-    PARTITION_NAND_ROOTFS2_LINK_NAME="/dev/partition_$(extract_nand_label "$PARTITION_NAND_ROOTFS2_DEV_NAME")"
-    PARTITION_NAND_HOME1_DEV_NAME="ubi0_1"
-    PARTITION_NAND_HOME1_LINK_NAME="/dev/partition_$(extract_nand_label "$PARTITION_NAND_HOME1_DEV_NAME")"
-
-    if $detach_ubi; then
-        /sbin/ubidetach --mtdn=8 &>/dev/null
-    fi
+# static partitions for systems with internal flash emmc
+ORDER="$(/etc/config-tools/get_typelabel_value ORDER)"
+if [[ "${ORDER:0:5}" == "751-9" ]]; then
+# CC100
+    PARTITION_EMMC_BOOT_DEV_NAME="mmcblk1p2"
+    PARTITION_EMMC_BOOT_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_BOOT_DEV_NAME")"
+    PARTITION_EMMC_ROOTFS1_DEV_NAME="mmcblk1p5"
+    PARTITION_EMMC_ROOTFS1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS1_DEV_NAME")"
+    PARTITION_EMMC_ROOTFS2_DEV_NAME="mmcblk1p8"
+    PARTITION_EMMC_ROOTFS2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS2_DEV_NAME")"
+    PARTITION_EMMC_HOME1_DEV_NAME="mmcblk1p6"
+    PARTITION_EMMC_HOME1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME1_DEV_NAME")"
+    PARTITION_EMMC_HOME2_DEV_NAME="mmcblk1p7"
+    PARTITION_EMMC_HOME2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME2_DEV_NAME")"
+    PARTITION_EMMC_LOG_DEV_NAME="mmcblk1p3"
+    PARTITION_EMMC_LOG_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_LOG_DEV_NAME")"
+    PARTITION_EMMC_SETTINGS_DEV_NAME="mmcblk1p4"
+    PARTITION_EMMC_SETTINGS_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_SETTINGS_DEV_NAME")"
 else
-    # static partitions for systems with internal flash emmc
-    ORDER="$(/etc/config-tools/get_typelabel_value ORDER)"
-    if [ "${ORDER:0:5}" == "751-9" ]; then
-      #CC100
-      PARTITION_EMMC_BOOT_DEV_NAME="mmcblk1p2"
-      PARTITION_EMMC_BOOT_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_BOOT_DEV_NAME")"
-      PARTITION_EMMC_ROOTFS1_DEV_NAME="mmcblk1p5"
-      PARTITION_EMMC_ROOTFS1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS1_DEV_NAME")"
-      PARTITION_EMMC_ROOTFS2_DEV_NAME="mmcblk1p8"
-      PARTITION_EMMC_ROOTFS2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS2_DEV_NAME")"
-      PARTITION_EMMC_HOME1_DEV_NAME="mmcblk1p6"
-      PARTITION_EMMC_HOME1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME1_DEV_NAME")"
-      PARTITION_EMMC_HOME2_DEV_NAME="mmcblk1p7"
-      PARTITION_EMMC_HOME2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME2_DEV_NAME")"
-      PARTITION_EMMC_LOG_DEV_NAME="mmcblk1p3"
-      PARTITION_EMMC_LOG_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_LOG_DEV_NAME")"
-      PARTITION_EMMC_SETTINGS_DEV_NAME="mmcblk1p4"
-      PARTITION_EMMC_SETTINGS_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_SETTINGS_DEV_NAME")"
-    else
-      #TP600
-      PARTITION_EMMC_BOOT_DEV_NAME="mmcblk1p1"
-      PARTITION_EMMC_BOOT_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_BOOT_DEV_NAME")"
-      PARTITION_EMMC_ROOTFS1_DEV_NAME="mmcblk1p7"
-      PARTITION_EMMC_ROOTFS1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS1_DEV_NAME")"
-      PARTITION_EMMC_ROOTFS2_DEV_NAME="mmcblk1p10"
-      PARTITION_EMMC_ROOTFS2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS2_DEV_NAME")"
-      PARTITION_EMMC_HOME1_DEV_NAME="mmcblk1p8"
-      PARTITION_EMMC_HOME1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME1_DEV_NAME")"
-      PARTITION_EMMC_HOME2_DEV_NAME="mmcblk1p9"
-      PARTITION_EMMC_HOME2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME2_DEV_NAME")"
-      PARTITION_EMMC_LOG_DEV_NAME="mmcblk1p5"
-      PARTITION_EMMC_LOG_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_LOG_DEV_NAME")"
-      PARTITION_EMMC_SETTINGS_DEV_NAME="mmcblk1p6"
-      PARTITION_EMMC_SETTINGS_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_SETTINGS_DEV_NAME")"
-    fi
+# PFC / TP600
+    PARTITION_EMMC_BOOT_DEV_NAME="mmcblk1p1"
+    PARTITION_EMMC_BOOT_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_BOOT_DEV_NAME")"
+    PARTITION_EMMC_ROOTFS1_DEV_NAME="mmcblk1p7"
+    PARTITION_EMMC_ROOTFS1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS1_DEV_NAME")"
+    PARTITION_EMMC_ROOTFS2_DEV_NAME="mmcblk1p10"
+    PARTITION_EMMC_ROOTFS2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS2_DEV_NAME")"
+    PARTITION_EMMC_HOME1_DEV_NAME="mmcblk1p8"
+    PARTITION_EMMC_HOME1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME1_DEV_NAME")"
+    PARTITION_EMMC_HOME2_DEV_NAME="mmcblk1p9"
+    PARTITION_EMMC_HOME2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME2_DEV_NAME")"
+    PARTITION_EMMC_LOG_DEV_NAME="mmcblk1p5"
+    PARTITION_EMMC_LOG_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_LOG_DEV_NAME")"
+    PARTITION_EMMC_SETTINGS_DEV_NAME="mmcblk1p6"
+    PARTITION_EMMC_SETTINGS_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_SETTINGS_DEV_NAME")"
 fi
 
 # get configured kbus uart from sys-fs
-if [ -e /dev/kbus0 ]; then
+if [[ -e /dev/kbus0 ]]; then
     KBUS_TTY_PFCXXX_DEV_NAME="$(cat /sys/class/wago/system/kbus_tty_device_name)"
     KBUS_TTY_PFCXXX_LINK_NAME="/dev/ttyKbus"
 fi
@@ -123,103 +108,107 @@ GSM_MODEM_TTY_PFCXXX_LINK_NAME="/dev/ttyRUNTIME66"
 # CC100
 TTY_CC100_RS485_DEV_NAME="ttySTM1"
 TTY_CC100_RS485_LINK_NAME="/dev/ttyRUNTIME0"
+TTY_CC100_COM2_DEV_NAME="ttySTM2"
+TTY_CC100_COM2_LINK_NAME="/dev/ttyRUNTIME1"
+
 
 # profibus dp uio device names
 PROFIBUS_DP_UIO_XINT_NAME="UIO_DPC31_XINT"
 PROFIBUS_DP_UIO_SYNC_NAME="UIO_DPC31_SYNC"
 
-if [ ! -f "${DEVS_TO_LINK}" ]; then
-        echo "${DEVS_TO_LINK} not found"
-        exit 1
+if [[ ! -f "${DEVS_TO_LINK}" ]]; then
+    echo "${DEVS_TO_LINK} not found"
+    exit 1
 fi
 
 # create list of device-paths
 index=0
 device_paths=()
 
-while read line; do
-        tmp_dev=$(find ${DEV_SEARCH_PATH} -iname ${line})
-        if [ ! -z "${tmp_dev}" ]; then
-                device_paths[$index]=${tmp_dev}
-                index=$(($index + 1))
-        else
-                echo "${line} not found in ${DEV_SEARCH_PATH}"
-        fi
+while read -r line; do
+    tmp_dev=$(find ${DEV_SEARCH_PATH} -iname "${line}")
+    if [[ -n "${tmp_dev}" ]]; then
+        device_paths[index]=${tmp_dev}
+        index=$((index + 1))
+    else
+        echo "${line} not found in ${DEV_SEARCH_PATH}"
+    fi
 done <${DEVS_TO_LINK}
 
-if [ ${#device_paths[@]} -eq 0 ]; then
-        echo "no device-paths found"
-        exit 1
+if [[ ${#device_paths[@]} -eq 0 ]]; then
+    echo "no device-paths found"
+    exit 1
 fi
 
 case $1 in
 
-  start)
+    start)
         # if device kbus0 exist the kernel supports KBus so from the userspace we can check if kbus0 exists
-        if [ -e /dev/kbus0 ]; then
-                if [ -c "/dev/${KBUS_TTY_PFCXXX_DEV_NAME}" ]; then
-                        ln -s /dev/${KBUS_TTY_PFCXXX_DEV_NAME} "${KBUS_TTY_PFCXXX_LINK_NAME}"
-                else
-                        echo "ERROR: could not set ${KBUS_TTY_PFCXXX_LINK_NAME}, kbus will not be active"
-                fi
+        if [[ -e /dev/kbus0 ]]; then
+            if [[ -c "/dev/${KBUS_TTY_PFCXXX_DEV_NAME}" ]]; then
+                ln -s "/dev/${KBUS_TTY_PFCXXX_DEV_NAME}" "${KBUS_TTY_PFCXXX_LINK_NAME}"
+            else
+                echo "ERROR: could not set ${KBUS_TTY_PFCXXX_LINK_NAME}, kbus will not be active"
+            fi
         fi
 
-        if [ -c "/dev/${SERIAL_TTY_PFCXXX_DEV_NAME}" ]; then
-                ln -s /dev/${SERIAL_TTY_PFCXXX_DEV_NAME} "${SERIAL_TTY_PFCXXX_LINK_NAME}"
-                echo "hardware-available=true" >"/etc/specific/features/rs232_485-interface"
-        else
-                echo "INFO: tty_rs232_485 is not available"
-                echo "hardware-available=false" >"/etc/specific/features/rs232_485-interface"
+        if [[ -c "/dev/${SERIAL_TTY_PFCXXX_DEV_NAME}" ]]; then
+            ln -s "/dev/${SERIAL_TTY_PFCXXX_DEV_NAME}" "${SERIAL_TTY_PFCXXX_LINK_NAME}"
         fi
 
-        if [ -c "/dev/${SERVICE_TTY_PFCXXX_DEV_NAME}" ]; then
-                ln -s /dev/${SERVICE_TTY_PFCXXX_DEV_NAME} "${SERVICE_TTY_PFCXXX_LINK_NAME}"
-                echo "hardware-available=true" >"/etc/specific/features/serial-service-interface"
+        if [[ -c "/dev/${SERVICE_TTY_PFCXXX_DEV_NAME}" ]]; then
+            ln -s "/dev/${SERVICE_TTY_PFCXXX_DEV_NAME}" "${SERVICE_TTY_PFCXXX_LINK_NAME}"
+            echo "hardware-available=true" >"/etc/specific/features/serial-service-interface"
         else
-                echo "ERROR: could not set ${SERVICE_TTY_PFCXXX_LINK_NAME}, getty will fail"
-                echo "hardware-available=false" >"/etc/specific/features/serial-service-interface"
+            echo "ERROR: could not set ${SERVICE_TTY_PFCXXX_LINK_NAME}, getty will fail"
+            echo "hardware-available=false" >"/etc/specific/features/serial-service-interface"
         fi
 
-        ln -s /dev/${GSM_MODEM_TTY_PFCXXX_DEV_NAME} "${GSM_MODEM_TTY_PFCXXX_LINK_NAME}"
+        if [[ -c "/dev/${GSM_MODEM_TTY_PFCXXX_DEV_NAME}" ]]; then
+            ln -s /dev/${GSM_MODEM_TTY_PFCXXX_DEV_NAME} "${GSM_MODEM_TTY_PFCXXX_LINK_NAME}"
+        fi
 
-        if $(lsuio | grep -q "$PROFIBUS_DP_UIO_XINT_NAME"); then
-                if $(lsuio | grep -q "$PROFIBUS_DP_UIO_SYNC_NAME"); then
-                        echo "hardware-available=true" >"/etc/specific/features/profibus-dp-slave"
-                else
-                        echo "INFO: PROFIBUS DP device \"$PROFIBUS_DP_UIO_SYNC_NAME\" not available"
-                        echo "hardware-available=false" >"/etc/specific/features/profibus-dp-slave"
-                fi
-        else
-                echo "INFO: PROFIBUS DP device \"$PROFIBUS_DP_UIO_XINT_NAME\" not available"
+        if lsuio | grep -q "$PROFIBUS_DP_UIO_XINT_NAME"; then
+            if lsuio | grep -q "$PROFIBUS_DP_UIO_SYNC_NAME"; then
+                echo "hardware-available=true" >"/etc/specific/features/profibus-dp-slave"
+            else
+                echo "INFO: PROFIBUS DP device \"$PROFIBUS_DP_UIO_SYNC_NAME\" not available"
                 echo "hardware-available=false" >"/etc/specific/features/profibus-dp-slave"
+            fi
+        else
+            echo "INFO: PROFIBUS DP device \"$PROFIBUS_DP_UIO_XINT_NAME\" not available"
+            echo "hardware-available=false" >"/etc/specific/features/profibus-dp-slave"
         fi
 
         for path in "${device_paths[@]}"; do
-                ln -s ${path} /dev/
+            ln -s "${path}" /dev/
         done
 
         # ----- internal flash partitions -----
-        if [[ -c "/dev/mtd8" ]]; then
-                ln -s /dev/${PARTITION_NAND_ROOTFS1_DEV_NAME}    "${PARTITION_NAND_ROOTFS1_LINK_NAME}"
-                ln -s /dev/${PARTITION_NAND_ROOTFS2_DEV_NAME}    "${PARTITION_NAND_ROOTFS2_LINK_NAME}"
-                ln -s /dev/${PARTITION_NAND_HOME1_DEV_NAME}      "${PARTITION_NAND_HOME1_LINK_NAME}"
-        else
-                ln -s /dev/${PARTITION_EMMC_BOOT_DEV_NAME}       "${PARTITION_EMMC_BOOT_LINK_NAME}"
-                ln -s /dev/${PARTITION_EMMC_ROOTFS1_DEV_NAME}    "${PARTITION_EMMC_ROOTFS1_LINK_NAME}"
-                ln -s /dev/${PARTITION_EMMC_ROOTFS2_DEV_NAME}    "${PARTITION_EMMC_ROOTFS2_LINK_NAME}"
-                ln -s /dev/${PARTITION_EMMC_HOME1_DEV_NAME}      "${PARTITION_EMMC_HOME1_LINK_NAME}"
-                ln -s /dev/${PARTITION_EMMC_HOME2_DEV_NAME}      "${PARTITION_EMMC_HOME2_LINK_NAME}"
-                ln -s /dev/${PARTITION_EMMC_LOG_DEV_NAME}        "${PARTITION_EMMC_LOG_LINK_NAME}"
-                ln -s /dev/${PARTITION_EMMC_SETTINGS_DEV_NAME}   "${PARTITION_EMMC_SETTINGS_LINK_NAME}"
-        fi
+        ln -s /dev/${PARTITION_EMMC_BOOT_DEV_NAME}       "${PARTITION_EMMC_BOOT_LINK_NAME}"
+        ln -s /dev/${PARTITION_EMMC_ROOTFS1_DEV_NAME}    "${PARTITION_EMMC_ROOTFS1_LINK_NAME}"
+        ln -s /dev/${PARTITION_EMMC_ROOTFS2_DEV_NAME}    "${PARTITION_EMMC_ROOTFS2_LINK_NAME}"
+        ln -s /dev/${PARTITION_EMMC_HOME1_DEV_NAME}      "${PARTITION_EMMC_HOME1_LINK_NAME}"
+        ln -s /dev/${PARTITION_EMMC_HOME2_DEV_NAME}      "${PARTITION_EMMC_HOME2_LINK_NAME}"
+        ln -s /dev/${PARTITION_EMMC_LOG_DEV_NAME}        "${PARTITION_EMMC_LOG_LINK_NAME}"
+        ln -s /dev/${PARTITION_EMMC_SETTINGS_DEV_NAME}   "${PARTITION_EMMC_SETTINGS_LINK_NAME}"
 
         # CC100 RS485
-        if [ -c "/dev/${TTY_CC100_RS485_DEV_NAME}" ]; then
+        if [[ -c "/dev/${TTY_CC100_RS485_DEV_NAME}" ]]; then
             ln -s /dev/${TTY_CC100_RS485_DEV_NAME} "${TTY_CC100_RS485_LINK_NAME}"
+            ORDER="$(/etc/config-tools/get_typelabel_value ORDER)"
+            if [[ "${ORDER:0:8}" == "751-9301" ]] || [[ "${ORDER:0:8}" == "751-9401" ]]; then
+                echo "hardware-available=false" >"/etc/specific/features/rs232_485-interface"
+            else
+                echo "hardware-available=true" >"/etc/specific/features/rs232_485-interface"
+            fi
+        fi
+        if [[ -c "/dev/${TTY_CC100_COM2_DEV_NAME}" ]]; then
+            ln -s /dev/${TTY_CC100_COM2_DEV_NAME} "${TTY_CC100_COM2_LINK_NAME}"
         fi
 
-  ;;
-  stop)
-  ;;
+    ;;
+    stop)
+    ;;
 
 esac
